### ISSUE TITLE
background postion %

### ISSUE THREAD

**Issue by michaelDotco2** [greenish/jquery-cover#3]
This is the best plugin so far to tackle ie8.

However it would be even better to be able to use more precise background positions such as percentages.

Do you have any plans to do this with this plugin?

**Comment by greenish** [comment]
Glad the plugin is helpfull!

Let me have a look at how easily I can implement more precise positioning.

**Comment by greenish** [comment]
Hey @michaelDotco2

How should the plugin behave for you? What would be the best case scenario?
What would you like to do? Do you have a use case that I can look at?    

Assuming you can define `position: 50% 50%` what would the result be?

I'm trying to wrap my head around this.

cheers

**Comment by michaelDotco2** [comment]
Yes exactly. The plugin would be better if you could accurately put in the background position
say: 
	
background-position: 50% 87%;
background-repeat: no-repeat;
background-size: cover;

This is more difficult than just putting a top and left position on the image as rather than being measured by the top left corner with css it is measured by the center point of the image.

**Comment by greenish** [comment]
I've had a look at this.

It's not possible to make this happen without moving the image with javascript onResize.
One of my goals when writing this plugin was to avoid exactly that. I also think that this is exactly the reason why IE8 is still working, since moving large images this often with JS can be jittery even in newer browsers.

jquery-cover is meant as a fall back, so I think I prefer to leave it light as it is.

cheers 
Philipp
